<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\*.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Protos\common.proto" />
    <None Remove="Protos\Unit.proto" />
    <None Remove="Protos\User.proto" />
    <None Remove="Protos\UserSchedule.proto" />
    <None Remove="Protos\UserSession.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />
    <PackageReference Include="MediatR" Version="12.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessControlSystem.Application\AccessControlSystem.Application.csproj" />
    <ProjectReference Include="..\AccessControlSystem.Contracts\AccessControlSystem.Contracts.csproj" />
    <ProjectReference Include="..\AccessControlSystem.DataAccess\AccessControlSystem.DataAccess.csproj" />
  </ItemGroup>

</Project>
