<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessControlSystem.Contracts\AccessControlSystem.Contracts.csproj" />
    <ProjectReference Include="..\AccessControlSystem.Domain\AccessControlSystem.Domain.csproj" />
  </ItemGroup>

</Project>
